export const allColors = {
    light: {
        inputBackground: '#636363',
        iconColor: '#FFF',
        background: '#3E3E41',
        border: '#707070',
        borderCurrency: '#FFF',
        regularText: '#FFFFFF',
        subText: '#C1C1C1',
        buttonEdit: '#515151',
        buttonOperation: '#E68C01',
        buttonNumber: '#868686',
    },
    dark: {
        inputBackground: '#636363',
        iconColor: '#FFF',
        background: '#3E3E41',
        border: '#707070',
        borderCurrency: '#FFF',
        regularText: '#FFFFFF',
        subText: '#CCCCCC',
        buttonEdit: '#515151',
        buttonOperation: '#E68C01',
        buttonNumber: '#868686',
    },
};
